version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: